ERROR OCCURS THEN THAT "except" BLOCK WILL EXECUTED AND ELSE "will" BE IGNORED
#        2. AND WHEN ERROR DO NOT OCCUR THEN "except" BLOCK WILL NOT BE EXECUTED AND "else" WILL BE EXECUTED
#        3. WHEN WE TRY TO EXECUTE SOMETHING THAT DON'T COMES UNDER THE EXCEPTION MENTIONED IN THE CODE THEN generic "except" WILL BE EXECUTED
#           Eg: in